# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf-8
  database: <%= ENV["database"] %>
  username: <%= ENV["username"] %>
  password: <%= ENV["password"] %>
  host: <%= ENV["host"] %>
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: iprop_test

production:
  <<: *default
  port: 5432
  timeout: 5000
