# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: 123

development:
  <<: *default
  database: iprop_development
test:
  <<: *default
  database: iprop_test

production:
  <<: *default
  database: db/production.sqlite3
